### ISSUE TITLE
Shutting down one bungee node causes errors on the others

### ISSUE THREAD

**Issue by Cobi** [minecrafter/RedisBungee#24]
I have permanently shutdown some bungee nodes in my network.

On the others, I see this:
`13:57:50 [SEVERE] [RedisBungee] REDACTED is 12087825835ms behind! (Time not synchronized or server down?)`

Is there something I need to do after shutting down a bungee node to prevent the above error?

**Comment by minecrafter** [comment]
RedisBungee will usually shut down gracefully. If you're force-killing BungeeCord, you need to issue an `HDEL heartbeats <server>` command to the Redis server used as well.
