### ISSUE TITLE
ProxyPingEvent

### ISSUE THREAD

**Issue by przemek3697** [minecrafter/RedisBungee#29]
Hey
Can u add to api method to register own plugin which modify ping respone?

**Comment by minecrafter** [comment]
No

**Comment by przemek3697** [comment]
``private static final List<String> ASYNC_PING_EVENT_HOSTILE = ImmutableList.of("ServerListPlus", "SwiftMOTD");``
Add my own plugin to this list :)
What I want to achieve its my own secret, but your plugin making some trouble for me ;)

**Comment by minecrafter** [comment]
I see. I will simply remove async ping event support, as it requires all sorts of hacks for most plugins.

**Comment by minecrafter** [comment]
Removed in  3b2d157.
