### ISSUE TITLE
getUUIDFromName(String) doesn't always work

### ISSUE THREAD

**Issue by ItsHarry** [minecrafter/RedisBungee#31]
getUUIDFromName(String) returns null even if the player is online on another proxy. I'm not sure if this was intended or a bug, but it would be logical for it to work if the player is actually online on the server.

It is rather significant for the plugin that I'm making that this actually works. Any chance this could be fixed?

**Comment by ItsHarry** [comment]
May have found the culprit:

None of the three calls to UUIDTranslator.persistInfo() use the name in lowercase, they use the actual username. Is this intended?

**Comment by minecrafter** [comment]
That's probably it. I'll go ahead and fix that when I have time.

**Comment by ItsHarry** [comment]
Okay, this causes getNameFromUUID to return names in lower case, I am going to send another pull request in a minute to fix this
