### ISSUE TITLE
Specific issue with domains

### ISSUE THREAD

**Issue by rourke750** [minecrafter/RedisBungee#37]
So on the current server I am on we are running into an issue where depending on the domain you use it will transfer you to a different server because of how this plugins handles server location based on domain connectivity.  Can you help me out in possibly pointing where I can look to change this behavior, I am capable of making the changes myself.

So like the intended behavior would want to be server1.mc.com and server2.mc.com connecting would take you to the last server you were on regardless of the domain you used.

**Comment by minecrafter** [comment]
This isn't a RedisBungee issue. You will need a reconnect handler that supports storing the last known server in something else other than a YAML flat file.
