### ISSUE TITLE
Ability to remove a dead server from redis

### ISSUE THREAD

**Issue by Samistine** [minecrafter/RedisBungee#42]
Able to remove this:
20:11:35 [SEVERE] [RedisBungee] test1 is 15928 seconds behind! (Time not synchronized or server down?)

**Comment by Moehritz** [comment]
You can do `HDEL heartbeats test1` using `redis-cli` to delete a server

**Comment by Chnkr** [comment]
Correct. shutting the server down cleanly will also help.


________________________________
