### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by friishon** [minecrafter/RedisBungee#50]
This plugin support daisy-chain?

**Comment by Foorack** [comment]
@friishon Hello, could you specify a bit what you mean with "daisy-chain"?

**Comment by friishon** [comment]
something like round robin
2 bungeecord server, when one is down all trafic go to the second bungeecord
if this imposible, do you know something to do it?

**Comment by sgdc3** [comment]
No, stop asking to everyone, bungeecord daisy chain is impossible, it causes many glitches, that's why it's blocked by bungeecord itself.

**Comment by sgdc3** [comment]
The only way you can do that is to use a plugin like LobbyBalancer that allows you to have many different sections of servers

**Comment by Moehritz** [comment]
@friishon "daisy-chain" is connecting through multiple bungees at once (you join on the first, that connects you to the second, this one connects you to a third bungee / or a server). Each player is connected to every bungee (there is literally no reason to do that, this practice is explicitly disabled by bungee itself)

while "round robin" means having them in parallel: you always get a connection `player <-> bungee <-> server`. Each player connects through one bungeecord. (Do this if you have too much players for one instance to handle -> RedisBungee will make syncing playercount, onlinestatus etc possible)

So what do you want? You mentioned both... (while they are completely different topics)

**Comment by sgdc3** [comment]
This is what he means: https://github.com/WaterfallMC/Waterfall/issues/147

**Comment by friishon** [comment]
So, i can't have multiple bungeecord servers for having different type os games?
Because i don't know how people can connect throught bungee 1 to bungee 2 and back to bungee 1

**Comment by sgdc3** [comment]
As i said you need a plugin such LobbyBalancer, id does exactly what you want on a single bungee instance.

**Comment by friishon** [comment]
thanks for the help, i will close this
