### ISSUE TITLE
Redisbungee is showing players as online and they are not.

### ISSUE THREAD

**Issue by Alexre** [minecrafter/RedisBungee#57]
Redis is showing me some players online in certain servers, and they aren't, I'm using a friends system (UltimateFriends) and it's showing many of my list online, if I use /find they are online too.

With /pproxy they are not, nor with /glist.

Tried to restart the proxies, nothing happens.

**Comment by skyslience** [comment]
when the player leave the server .maybe the redis remove the player info failed. so,when the player join the server .the player is online

**Comment by Chnkr** [comment]
Sounds like your Redis server is having issues

**Comment by skyslience** [comment]
yes my server is having the issues

**Comment by Chnkr** [comment]
Resolved
