### ISSUE TITLE
plugin messaging  1.13 support

### ISSUE THREAD

**Issue by Duartteno** [minecrafter/RedisBungee#60]
Hello, can you add support to 1.13?

**Comment by sgdc3** [comment]
@detobel36 plugin messaging is supposed to be broken due to the new channel name format

**Comment by Matiyeu** [comment]
@detobel36 Your commit doesn't work with versions older than 1.13

**Comment by detobel36** [comment]
@Matiyeu we already discuss that in the pull request.... 
    
I just push a new version where I hope this will work.

**Comment by Chnkr** [comment]
Resolved trough 429ed39 sorry for the delay :)
