### ISSUE TITLE
Load balancer between different bungeecord servers not working

### ISSUE THREAD

**Issue by YusufYaser** [minecrafter/RedisBungee#80]
Hello!

I have a server where I have 2 bungeecord servers using redis. But only players join the first bungeecord server, and the second is empty.

**Comment by detobel36** [comment]
Hi,

How your players join the server ?  They use an IP address or a domain name ?   
RedisBungee doesn't manage the "load balancer".  It just make the link between the two bungee instance.

The "load balancing" could be done with DNS. You define the same domain name to two different IP address.  If you don't use a domain name, you need to "create" a "load balancer".

**Comment by YusufYaser** [comment]
DNS thing is working for me. Thank you for your help!

**Comment by Lazylllama** [comment]
Amongus

**Comment by Lazylllama** [comment]
Rlly this is what ur doing on christmas`? some bungee shit??
